import type { ContentItem, Notification, Era } from './types';

export const eras: Era[] = ['Debut', 'Border: Day One', 'Border: Carnival', 'Dimension: Dilemma', 'Manifesto: Day 1', 'Dark Blood', 'Orange Blood'];

export const contentItems: ContentItem[] = [
  {
    id: '1',
    type: 'Video',
    title: 'ENHYPEN (엔하이픈) "Given-Taken" Official MV',
    description: 'The official music video for ENHYPEN\'s debut title track "Given-Taken".',
    date: '2020-11-30',
    era: 'Border: Day One',
    imageUrl: 'https://picsum.photos/seed/enhypen1/600/400',
    sourceUrl: 'https://www.youtube.com/watch?v=nQ6wEfS_f_E',
  },
  {
    id: '2',
    type: 'Photo',
    title: 'BORDER : DAY ONE - Concept Photo "DAWN"',
    description: 'Concept photos for the DAWN version of the album BORDER : DAY ONE.',
    date: '2020-11-21',
    era: 'Border: Day One',
    imageUrl: 'https://picsum.photos/seed/enhypen2/600/400',
    sourceUrl: '#',
  },
  {
    id: '3',
    type: 'News',
    title: 'ENHYPEN Makes Hot 100 Debut on Billboard Japan',
    description: 'ENHYPEN has made a remarkable debut on the Billboard Japan Hot 100 chart with their first mini-album "BORDER : DAY ONE".',
    date: '2020-12-09',
    era: 'Border: Day One',
    imageUrl: 'https://picsum.photos/seed/enhypen3/600/400',
    sourceUrl: '#',
  },
  {
    id: '4',
    type: 'Video',
    title: 'ENHYPEN (엔하이픈) "Drunk-Dazed" Official MV',
    description: 'The official music video for ENHYPEN\'s title track "Drunk-Dazed" from their second mini-album BORDER : CARNIVAL.',
    date: '2021-04-26',
    era: 'Border: Carnival',
    imageUrl: 'https://picsum.photos/seed/enhypen4/600/400',
    sourceUrl: 'https://www.youtube.com/watch?v=Fc7-Oe0VudM',
  },
  {
    id: '5',
    type: 'Photo',
    title: 'BORDER : CARNIVAL - Concept Photo "UP"',
    description: 'Concept photos for the UP version of the album BORDER : CARNIVAL.',
    date: '2021-04-18',
    era: 'Border: Carnival',
    imageUrl: 'https://picsum.photos/seed/enhypen5/600/400',
    sourceUrl: '#',
    memberIds: ['1', '2']
  },
  {
    id: '6',
    type: 'Video',
    title: 'ENHYPEN (엔하이픈) "Tamed-Dashed" Official MV',
    description: 'The official music video for "Tamed-Dashed" from the album DIMENSION : DILEMMA.',
    date: '2021-10-12',
    era: 'Dimension: Dilemma',
    imageUrl: 'https://picsum.photos/seed/enhypen6/600/400',
    sourceUrl: 'https://www.youtube.com/watch?v=6IRsW_TkyQI',
  },
  {
    id: '7',
    type: 'News',
    title: 'ENHYPEN Achieves "Million-Seller" Status with First Full Album',
    description: 'ENHYPEN\'s first studio album "DIMENSION : DILEMMA" has sold over one million copies, earning them the "million-seller" title.',
    date: '2021-11-11',
    era: 'Dimension: Dilemma',
    imageUrl: 'https://picsum.photos/seed/enhypen7/600/400',
    sourceUrl: '#',
    memberIds: ['3', '4']
  },
  {
    id: '8',
    type: 'Video',
    title: 'ENHYPEN (엔하이픈) "Future Perfect (Pass the MIC)" Official MV',
    description: 'The official music video for "Future Perfect (Pass the MIC)" from the mini-album MANIFESTO : DAY 1.',
    date: '2022-07-04',
    era: 'Manifesto: Day 1',
    imageUrl: 'https://picsum.photos/seed/enhypen8/600/400',
    sourceUrl: 'https://www.youtube.com/watch?v=T--r51t5c50',
  },
  {
    id: '9',
    type: 'Photo',
    title: 'MANIFESTO : DAY 1 - Concept Photo "D"',
    description: 'Concept photos for the D version of the album MANIFESTO : DAY 1.',
    date: '2022-06-25',
    era: 'Manifesto: Day 1',
    imageUrl: 'https://picsum.photos/seed/enhypen9/600/400',
    sourceUrl: '#',
    memberIds: ['5', '6']
  },
  {
    id: '10',
    type: 'Video',
    title: 'ENHYPEN (엔하이픈) "Bite Me" Official MV',
    description: 'The official music video for "Bite Me" from the mini-album DARK BLOOD.',
    date: '2023-05-22',
    era: 'Dark Blood',
    imageUrl: 'https://picsum.photos/seed/enhypen10/600/400',
    sourceUrl: 'https://www.youtube.com/watch?v=wXFLzODb81I',
  },
  {
    id: '11',
    type: 'Photo',
    title: 'DARK BLOOD - Concept Photo "FULL"',
    description: 'Concept photos for the FULL version of the album DARK BLOOD.',
    date: '2023-05-07',
    era: 'Dark Blood',
    imageUrl: 'https://picsum.photos/seed/enhypen11/600/400',
    sourceUrl: '#',
    memberIds: ['7']
  },
  {
    id: '12',
    type: 'News',
    title: 'ENHYPEN to Embark on Second World Tour "FATE"',
    description: 'ENHYPEN announces their second world tour, "FATE," with initial dates in Seoul and Japan.',
    date: '2023-05-31',
    era: 'Dark Blood',
    imageUrl: 'https://picsum.photos/seed/enhypen12/600/400',
    sourceUrl: '#',
  },
    {
    id: '13',
    type: 'Video',
    title: 'ENHYPEN (엔하이픈) "Sweet Venom" Official MV',
    description: 'The official music video for "Sweet Venom" from the mini-album ORANGE BLOOD.',
    date: '2023-11-17',
    era: 'Orange Blood',
    imageUrl: 'https://picsum.photos/seed/enhypen13/600/400',
    sourceUrl: 'https://www.youtube.com/watch?v=qed0_niI7Lw',
  },
  {
    id: '14',
    type: 'Photo',
    title: 'ORANGE BLOOD - Concept Photo "KSANA"',
    description: 'Concept photos for the KSANA version of the album ORANGE BLOOD.',
    date: '2023-11-05',
    era: 'Orange Blood',
    imageUrl: 'https://picsum.photos/seed/enhypen14/600/400',
    sourceUrl: '#',
  },
  {
    id: '15',
    type: 'News',
    title: 'Enhypen\'s "Orange Blood" debuts at No. 4 on Billboard 200',
    description: 'Enhypen\'s latest EP has debuted at number four on the Billboard 200 albums chart.',
    date: '2023-11-28',
    era: 'Orange Blood',
    imageUrl: 'https://picsum.photos/seed/enhypen15/600/400',
    sourceUrl: '#',
  },
];

export const notifications: Notification[] = [
    {
        id: '1',
        title: 'New Video: "Sweet Venom" MV Released',
        description: 'The official music video for Sweet Venom is out now!',
        date: '2023-11-17'
    },
    {
        id: '2',
        title: 'Content Library Updated',
        description: 'New concept photos for ORANGE BLOOD have been added.',
        date: '2023-11-05'
    },
    {
        id: '3',
        title: 'AI Discovery Complete',
        description: 'Found 3 new articles about the "FATE" world tour.',
        date: '2023-05-31'
    }
]
