import { Member } from './types';

export const members: Member[] = [
  {
    id: '1',
    slug: 'heeseung',
    name: 'Heeseung',
    koreanName: '이희승',
    birthDate: '2001-10-15',
    position: 'Vocalist, Dancer',
    emoji: '🦌',
    avatarUrl: 'https://picsum.photos/seed/heeseung/400/400',
    bio: 'Lee Heeseung is the oldest member of ENHYPEN. Known for his exceptional vocal and dance skills, he is often called the "ace" of the group. He trained for over three years and was a popular trainee even before participating in I-LAND.',
    soloActivities: [
      { title: 'Cover: "Off My Face" (Justin Bieber)', date: '2022-05-30', url: 'https://www.youtube.com/watch?v=k3n-RU41r_c' },
    ],
  },
  {
    id: '2',
    slug: 'jay',
    name: 'Jay',
    koreanName: '제이',
    birthDate: '2002-04-20',
    position: 'Dancer, Rapper, Vocalist',
    emoji: '🦅',
    avatarUrl: 'https://picsum.photos/seed/jay/400/400',
    bio: 'Jay Park, born in the United States, is known for his powerful dance moves and charismatic stage presence. He is also fluent in English and often takes the lead in international interviews. His fashion sense is notable among fans.',
    soloActivities: [
       { title: 'Regular Host: "JAY-PO"', date: '2023-present', url: '#' },
    ],
  },
  {
    id: '3',
    slug: 'jake',
    name: 'Jake',
    koreanName: '제이크',
    birthDate: '2002-11-15',
    position: 'Vocalist, Rapper, Dancer',
    emoji: '🐶',
    avatarUrl: 'https://picsum.photos/seed/jake/400/400',
    bio: 'Jake Sim, who grew up in Australia, is cherished for his sweet personality and charming visuals. He passed the global auditions with a 500:1 competition rate and has shown immense growth as an artist since his debut.',
    soloActivities: [
        { title: 'Cover: "Let Me In (20 CUBE)" Acoustic Ver.', date: '2021-03-12', url: 'https://www.youtube.com/watch?v=G8_4s4v2T3A' },
    ],
  },
  {
    id: '4',
    slug: 'sunghoon',
    name: 'Sunghoon',
    koreanName: '박성훈',
    birthDate: '2002-12-08',
    position: 'Vocalist, Dancer, Visual',
    emoji: '🐧',
    avatarUrl: 'https://picsum.photos/seed/sunghoon/400/400',
    bio: 'Park Sunghoon was a professional figure skater before becoming an idol, winning multiple international competitions. His elegance and precision from skating translate beautifully into his dance performances. He was also an MC for Music Bank.',
    soloActivities: [
      { title: 'MC for KBS Music Bank', date: '2021-2022', url: '#' },
    ],
  },
  {
    id: '5',
    slug: 'sunoo',
    name: 'Sunoo',
    koreanName: '김선우',
    birthDate: '2003-06-24',
    position: 'Vocalist',
    emoji: '🦊',
    avatarUrl: 'https://picsum.photos/seed/sunoo/400/400',
    bio: 'Kim Sunoo is known for his bright, energetic personality and expressive facial expressions on stage, which earned him the title "master of expressions." He is a vital source of positivity within the group.',
    soloActivities: [
        { title: 'Web Show: "SUNOO\'s Curiosity Research Center"', date: '2021', url: 'https://www.youtube.com/watch?v=hB93f0aj2m4' },
    ],
  },
  {
    id: '6',
    slug: 'jungwon',
    name: 'Jungwon',
    koreanName: '양정원',
    birthDate: '2004-02-09',
    position: 'Leader, Vocalist, Dancer',
    emoji: '🐈',
    avatarUrl: 'https://picsum.photos/seed/jungwon/400/400',
    bio: 'Yang Jungwon is the charismatic and reliable leader of ENHYPEN. Despite his young age, he leads the group with maturity and a strong sense of responsibility. He has a background in Taekwondo, which contributes to his powerful dance style.',
    soloActivities: [
        { title: 'Cover: "I Like Me Better" (Lauv)', date: '2022-07-27', url: 'https://www.youtube.com/watch?v=3z_sT9tqgRA' },
    ],
  },
  {
    id: '7',
    slug: 'ni-ki',
    name: 'Ni-ki',
    koreanName: '니키',
    birthDate: '2005-12-09',
    position: 'Main Dancer, Rapper, Maknae',
    emoji: '🐆',
    avatarUrl: 'https://picsum.photos/seed/ni-ki/400/400',
    bio: 'Nishimura Riki, known as Ni-ki, is the Japanese youngest member (maknae) and main dancer of the group. He was a backup dancer for SHINee and is widely recognized for his incredible dance talent and ability to learn choreography quickly.',
    soloActivities: [
      { title: 'Artist Of The Month Dance Performance', date: '2021-06-23', url: 'https://www.youtube.com/watch?v=b4k2Rj1a-gE' },
    ],
  },
];
